import { Translation, Language } from './types';

export const CLINIC_INFO = {
  name: "Dr. Luxe Aesthetic Clinic",
  rating: 4.8,
  reviewCount: 124,
  address: "C. de Serrano, 45, Salamanca, 28001 Madrid, Spain",
  phone: "+34 912 34 56 78",
  whatsapp: "https://wa.me/34912345678",
  hours: [
    { day: "Monday", time: "10:00 AM - 8:00 PM", isOpen: true },
    { day: "Tuesday", time: "10:00 AM - 8:00 PM", isOpen: true },
    { day: "Wednesday", time: "10:00 AM - 8:00 PM", isOpen: true },
    { day: "Thursday", time: "10:00 AM - 8:00 PM", isOpen: true },
    { day: "Friday", time: "10:00 AM - 8:00 PM", isOpen: true },
    { day: "Saturday", time: "10:00 AM - 2:00 PM", isOpen: true },
    { day: "Sunday", time: "Closed", isOpen: false },
  ]
};

export const TRANSLATIONS: Record<Language, Translation> = {
  en: {
    bookNow: "BOOK NOW",
    overview: "Overview",
    reviews: "Reviews",
    about: "About",
    directions: "Directions",
    elevate: "Elevate Your",
    naturalBeauty: "Natural Beauty",
    heroDesc: "Madrid's premier destination for advanced medical aesthetics. We combine scientific precision with an artistic eye to deliver transformative results.",
    explore: "EXPLORE TREATMENTS",
    viewGallery: "VIEW GALLERY",
    nextAvailable: "Next Available",
    tomorrow: "Tomorrow, 10:30 AM",
    quickBook: "Quick Book",
    openNow: "Open now",
    closes: "Closes 8:00 PM",
    theClinic: "The Clinic",
    patientStories: "Patient Stories",
    visitUs: "Visit Us",
    address: "Address",
    hours: "Hours",
    phone: "Phone",
    whatsappUs: "WhatsApp Us",
    bookAppointment: "Book Appointment",
    womenOwned: "Identifies as women-owned",
    save: "Save",
    nearby: "Nearby",
    sendToPhone: "Send to phone",
    share: "Share"
  },
  fr: {
    bookNow: "RÉSERVER",
    overview: "Aperçu",
    reviews: "Avis",
    about: "À propos",
    directions: "Itinéraire",
    elevate: "Sublimez Votre",
    naturalBeauty: "Beauté Naturelle",
    heroDesc: "La destination de premier choix à Madrid pour l'esthétique médicale avancée. Nous combinons précision scientifique et regard artistique.",
    explore: "EXPLORER LES SOINS",
    viewGallery: "VOIR LA GALERIE",
    nextAvailable: "Prochain RDV",
    tomorrow: "Demain, 10h30",
    quickBook: "Réservation Rapide",
    openNow: "Ouvert",
    closes: "Ferme à 20h00",
    theClinic: "La Clinique",
    patientStories: "Témoignages",
    visitUs: "Nous Visiter",
    address: "Adresse",
    hours: "Horaires",
    phone: "Téléphone",
    whatsappUs: "WhatsApp",
    bookAppointment: "Prendre RDV",
    womenOwned: "Entreprise gérée par des femmes",
    save: "Enregistrer",
    nearby: "À proximité",
    sendToPhone: "Envoyer au tél",
    share: "Partager"
  },
  es: {
    bookNow: "RESERVAR",
    overview: "Resumen",
    reviews: "Reseñas",
    about: "Sobre nosotros",
    directions: "Cómo llegar",
    elevate: "Eleva Tu",
    naturalBeauty: "Belleza Natural",
    heroDesc: "El destino principal de Madrid para la estética médica avanzada. Combinamos precisión científica con un ojo artístico.",
    explore: "EXPLORAR TRATAMIENTOS",
    viewGallery: "VER GALERÍA",
    nextAvailable: "Próximo Disponible",
    tomorrow: "Mañana, 10:30 AM",
    quickBook: "Reserva Rápida",
    openNow: "Abierto ahora",
    closes: "Cierra a las 8:00 PM",
    theClinic: "La Clínica",
    patientStories: "Historias de Pacientes",
    visitUs: "Visítanos",
    address: "Dirección",
    hours: "Horarios",
    phone: "Teléfono",
    whatsappUs: "WhatsApp",
    bookAppointment: "Reservar Cita",
    womenOwned: "Identificado como propiedad de mujeres",
    save: "Guardar",
    nearby: "Cerca",
    sendToPhone: "Enviar al móvil",
    share: "Compartir"
  },
  ar: {
    bookNow: "احجز الآن",
    overview: "نظرة عامة",
    reviews: "المراجعات",
    about: "حول",
    directions: "الاتجاهات",
    elevate: "ارتقِ بـ",
    naturalBeauty: "جمالك الطبيعي",
    heroDesc: "وجهة مدريد الأولى للجمال الطبي المتقدم. نجمع بين الدقة العلمية والنظرة الفنية لتقديم نتائج مذهلة.",
    explore: "استكشف العلاجات",
    viewGallery: "عرض المعرض",
    nextAvailable: "الموعد المتاح التالي",
    tomorrow: "غداً، 10:30 صباحاً",
    quickBook: "حجز سريع",
    openNow: "مفتوح الآن",
    closes: "يغلق الساعة 8:00 مساءً",
    theClinic: "العيادة",
    patientStories: "قصص المرضى",
    visitUs: "تفضل بزيارتنا",
    address: "العنوان",
    hours: "الساعات",
    phone: "الهاتف",
    whatsappUs: "واتساب",
    bookAppointment: "حجز موعد",
    womenOwned: "تدار من قبل النساء",
    save: "حفظ",
    nearby: "قريب",
    sendToPhone: "إرسال إلى الهاتف",
    share: "مشاركة"
  },
  it: {
    bookNow: "PRENOTA ORA",
    overview: "Panoramica",
    reviews: "Recensioni",
    about: "Chi siamo",
    directions: "Indicazioni",
    elevate: "Eleva la Tua",
    naturalBeauty: "Belleza Naturale",
    heroDesc: "La destinazione principale di Madrid per l'estetica medica avanzata. Combiniamo precisione scientifica e occhio artistico.",
    explore: "ESPLORA TRATTAMENTI",
    viewGallery: "VEDI GALLERIA",
    nextAvailable: "Prossimo Disponibile",
    tomorrow: "Domani, 10:30",
    quickBook: "Prenotazione Rapida",
    openNow: "Aperto ora",
    closes: "Chiude alle 20:00",
    theClinic: "La Clinica",
    patientStories: "Storie dei Pazienti",
    visitUs: "Vieni a Trovarci",
    address: "Indirizzo",
    hours: "Orari",
    phone: "Telefono",
    whatsappUs: "WhatsApp",
    bookAppointment: "Prenota Appuntamento",
    womenOwned: "Gestito da donne",
    save: "Salva",
    nearby: "Nelle vicinanze",
    sendToPhone: "Invia al telefono",
    share: "Condividi"
  }
};
